# -*- coding: utf-8 -*-
"""List_Less_Than_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOAK4bL1sla5eZXKS7KMQs6mgOABLVKV

List Less Than Ten

https://www.practicepython.org/exercise/2014/02/15/03-list-less-than-ten.html
"""

# find elements that are less than 5 in list comprehension

usr_inpt = int(input('enter a value: '))

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

solution = [a[i] for i in range(len(a)) if a[i] < usr_inpt]

print(solution)

# find elements that are less than 5

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

solution = []

for i in range(len(a)):
  if a[i] < 5:
    solution.append(a[i])
    print(f'iteration {i + 1}: {a[i]}')

print(solution)