# -*- coding: utf-8 -*-
"""Odd_or_Even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHyiGKmkmGPV5TCNh5oIm6C9TKB0zSUc

Odd or Even

https://www.practicepython.org/exercise/2014/02/05/02-odd-or-even.html
"""

# gain user input and reply with even or odd

def usr_inpt():
  while True:
    try:
      usr_inpt.user_num = int(input('please enter a number: '))
      break
    except ValueError:
      print('please enter a whole number')

  if usr_inpt.user_num == 0:
    print('div err')
  elif usr_inpt.user_num % 4 == 0:
    print('multiple of 4')
  elif usr_inpt.user_num % 2 == 0:
    print('even')
  else:
    print('odd')

usr_inpt()

# obtain user input for 2 numbers and divide them to check if they divide evenly

def evn_chk():
  while True:
    try:
      evn_chk.num = int(input('enter a numerator: '))
      evn_chk.den = int(input('enter a denomenator: '))
      break
    except ValueError:
      print('please enter a whole number')

  check = int(evn_chk.num / evn_chk.den)

  if check % 2 == 0:
    print(f'even: {check}')
  else:
    print(f'odd: {check}')

evn_chk()